name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ${{ vars.LINUX }}
    timeout-minutes: 10

    env:
      MAILOSAUR_BASE_URL: https://mailosaur.com/
      MAILOSAUR_SMTP_HOST: mailosaur.net
      MAILOSAUR_SMTP_PORT: 2525
      MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
      MAILOSAUR_SERVER: ${{ secrets.MAILOSAUR_SERVER }}
      MAILOSAUR_VERIFIED_DOMAIN: ${{ secrets.MAILOSAUR_VERIFIED_DOMAIN }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Checkout custom actions
        uses: actions/checkout@v4
        with:
          repository: mailosaur/actions
          token: ${{ secrets.CUSTOM_ACTIONS_TOKEN }}
          path: .github/actions
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: jetbrains
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Version
        run: |
          version=`git describe --abbrev=0 --tags` &&	
          sed -i s/\[0-9]\.\[0-9]\.\[0-9]/$version/ src/main/java/com/mailosaur/MailosaurClient.java && 
          mvn versions:set -DnewVersion=$version
      - name: Publish
        run: |
          mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Send notifications
        if: ${{ always() }}
        uses: ./.github/actions/notify
        with:
          webhook-url: ${{ secrets.NOTIFICATION_URL }}
